spring:
  application:
    name: mater-imperium-test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/mater
    username: sentimento
    password: 74185296
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/db-changelog-main.xml

security:
  jwt:
    secret-key: 5fa03385869ed1e37ea5dba34940868e09552a40e9f66428f93eb484ad311be6
    expiration-time: 3600000


jwt:
  token:
    prefix: Bearer
    validity: 18000
  signing:
    key: YourSignInKey
  authorities:
    key: roles
  header:
    string: Authorization